#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("pl_AutoNumbering_GetNewNumber")]
	public partial class pl_AutoNumbering_GetNewNumberRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Entity
		{
			get
			{
				if (this.Parameters.Contains("Entity"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Entity"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Entity"] = value;
			}
		}
		
		public System.Guid ParentEntityId
		{
			get
			{
				if (this.Parameters.Contains("ParentEntityId"))
				{
					return ((System.Guid)(this.Parameters["ParentEntityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["ParentEntityId"] = value;
			}
		}
		
		public pl_AutoNumbering_GetNewNumberRequest()
		{
			this.RequestName = "pl_AutoNumbering_GetNewNumber";
			this.Entity = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("pl_AutoNumbering_GetNewNumber")]
	public partial class pl_AutoNumbering_GetNewNumberResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public pl_AutoNumbering_GetNewNumberResponse()
		{
		}
		
		public string Number
		{
			get
			{
				if (this.Results.Contains("Number"))
				{
					return ((string)(this.Results["Number"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Number"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
