trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  frameworkProject: 'src/Pillaro.Dataverse.PluginFramework/Pillaro.Dataverse.PluginFramework.csproj'
  nuspecPath: 'src/Pillaro.Dataverse.PluginFramework/Tools/PluginPackaging/Pillaro.Dataverse.PluginFramework.nuspec'
  Major: 1
  Minor: 0
  Patch: 0

name: '$(Major).$(Minor).$(Patch)-ci.$(Rev:r)'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: NuGetCommand@2
    displayName: 'NuGet Restore'
    inputs:
      command: 'restore'
      restoreSolution: '$(frameworkProject)'

  - task: VSBuild@1
    displayName: 'Build PluginFramework'
    inputs:
      solution: '$(frameworkProject)'
      configuration: '$(buildConfiguration)'

  - task: NuGetCommand@2
    displayName: 'Pack PluginFramework'
    inputs:
      command: 'pack'
      packagesToPack: '$(nuspecPath)'
      configuration: '$(buildConfiguration)'
      versioningScheme: 'byBuildNumber'
      packDestination: '$(Build.ArtifactStagingDirectory)'
      buildProperties: 'configuration=$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish NuGet artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nuget-package'