#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum crd8e_pl_autonumbering_pl_useparentconfiguration
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ano = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ne = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel3 = 3,
	}
	
	/// <summary>
	/// Status of the Autonumbering
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pl_autonumbering_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Autonumbering
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pl_autonumbering_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("pl_autonumbering")]
	public partial class pl_AutoNumbering : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the pl_autonumbering entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string pl_AutoNumberingId = "pl_autonumberingid";
			public const string Id = "pl_autonumberingid";
			public const string pl_Customer = "pl_customer";
			public const string pl_DateFormat1 = "pl_dateformat1";
			public const string pl_DateFormat2 = "pl_dateformat2";
			public const string pl_DateFormat3 = "pl_dateformat3";
			public const string pl_DigitCount = "pl_digitcount";
			public const string pl_EntityName = "pl_entityname";
			public const string pl_File = "pl_file";
			public const string pl_FormatString = "pl_formatstring";
			public const string pl_GroupingValue = "pl_groupingvalue";
			public const string pl_Number = "pl_number";
			public const string pl_ParentAutoNumberingId = "pl_parentautonumberingid";
			public const string pl_ParentLookupAttribute = "pl_parentlookupattribute";
			public const string pl_ParentLookupId = "pl_parentlookupid";
			public const string pl_UseParentConfiguration = "pl_useparentconfiguration";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string Referencedpl_AutoNumbering_AutoNumbering_ParentAutoNumberingId = "Referencedpl_AutoNumbering_AutoNumbering_ParentAutoNumberingId";
			public const string Referencingpl_AutoNumbering_AutoNumbering_ParentAutoNumberingId = "pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public pl_AutoNumbering() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "pl_autonumbering";
		
		public const string EntityLogicalCollectionName = "pl_autonumberings";
		
		public const string EntitySetName = "pl_autonumberings";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_autonumberingid")]
		public System.Nullable<System.Guid> pl_AutoNumberingId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("pl_autonumberingid");
			}
			set
			{
				this.SetAttributeValue("pl_autonumberingid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_autonumberingid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.pl_AutoNumberingId = value;
			}
		}
		
		/// <summary>
		/// Zákazník
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_customer")]
		public Microsoft.Xrm.Sdk.EntityReference pl_Customer
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pl_customer");
			}
			set
			{
				this.SetAttributeValue("pl_customer", value);
			}
		}
		
		/// <summary>
		/// Enter the standard string for date formatting (e.g. yyyy for a four-digit year). For more information, see Standard Date and Time Format Strings. Use {date1} in the field Format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_dateformat1")]
		public string pl_DateFormat1
		{
			get
			{
				return this.GetAttributeValue<string>("pl_dateformat1");
			}
			set
			{
				this.SetAttributeValue("pl_dateformat1", value);
			}
		}
		
		/// <summary>
		/// Enter the standard string for date formatting (e.g. yyyy for a four-digit year). For more information, see Standard Date and Time Format Strings. Use {date2} in the field Format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_dateformat2")]
		public string pl_DateFormat2
		{
			get
			{
				return this.GetAttributeValue<string>("pl_dateformat2");
			}
			set
			{
				this.SetAttributeValue("pl_dateformat2", value);
			}
		}
		
		/// <summary>
		/// Enter the standard string for date formatting (e.g. yyyy for a four-digit year). For more information, see Standard Date and Time Format Strings. Use {date3} in the field Format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_dateformat3")]
		public string pl_DateFormat3
		{
			get
			{
				return this.GetAttributeValue<string>("pl_dateformat3");
			}
			set
			{
				this.SetAttributeValue("pl_dateformat3", value);
			}
		}
		
		/// <summary>
		/// How many digits the automatic number should have. For example, if it is 4 and the next automatic number is 10, it will be displayed as 0010.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_digitcount")]
		public System.Nullable<int> pl_DigitCount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pl_digitcount");
			}
			set
			{
				this.SetAttributeValue("pl_digitcount", value);
			}
		}
		
		/// <summary>
		/// The system name of the entity into which the automatic number is inserted (e.g. invoice).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_entityname")]
		public string pl_EntityName
		{
			get
			{
				return this.GetAttributeValue<string>("pl_entityname");
			}
			set
			{
				this.SetAttributeValue("pl_entityname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_file")]
		public System.Nullable<System.Guid> pl_File
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("pl_file");
			}
		}
		
		/// <summary>
		/// Format of the automatic number. The elements of the format are described below. E.g. for "F00231-25" enter F{NUM}-{date1}
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_formatstring")]
		public string pl_FormatString
		{
			get
			{
				return this.GetAttributeValue<string>("pl_formatstring");
			}
			set
			{
				this.SetAttributeValue("pl_formatstring", value);
			}
		}
		
		/// <summary>
		/// This value is used to distinguish the period for which the series applies (e.g. the year of the taxable supply date in accounting documents).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_groupingvalue")]
		public string pl_GroupingValue
		{
			get
			{
				return this.GetAttributeValue<string>("pl_groupingvalue");
			}
			set
			{
				this.SetAttributeValue("pl_groupingvalue", value);
			}
		}
		
		/// <summary>
		/// The last generated assigned number. Use {NUM} in the field Format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_number")]
		public System.Nullable<int> pl_Number
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pl_number");
			}
			set
			{
				this.SetAttributeValue("pl_number", value);
			}
		}
		
		/// <summary>
		/// Link to the parent configuration of autonumbering. It is used where subordinate configurations are automatically generated according to the parent entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_parentautonumberingid")]
		public Microsoft.Xrm.Sdk.EntityReference pl_ParentAutoNumberingId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pl_parentautonumberingid");
			}
			set
			{
				this.SetAttributeValue("pl_parentautonumberingid", value);
			}
		}
		
		/// <summary>
		/// The system field name for a lookup to the parent entity (e.g. accountid or pl_contactid.parentcustomerid). Separate numerical sequences will be generated based on this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_parentlookupattribute")]
		public string pl_ParentLookupAttribute
		{
			get
			{
				return this.GetAttributeValue<string>("pl_parentlookupattribute");
			}
			set
			{
				this.SetAttributeValue("pl_parentlookupattribute", value);
			}
		}
		
		/// <summary>
		/// Parent Entity Primary Id (guid)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_parentlookupid")]
		public string pl_ParentLookupId
		{
			get
			{
				return this.GetAttributeValue<string>("pl_parentlookupid");
			}
			set
			{
				this.SetAttributeValue("pl_parentlookupid", value);
			}
		}
		
		/// <summary>
		/// For the subordinate configuration – whether the configuration should be taken from it or from the parent configuration. The subordinate entity does not have filled attributes that are taken from the parent configuration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_useparentconfiguration")]
		public virtual crd8e_pl_autonumbering_pl_useparentconfiguration? pl_UseParentConfiguration
		{
			get
			{
				return ((crd8e_pl_autonumbering_pl_useparentconfiguration?)(EntityOptionSetEnum.GetEnum(this, "pl_useparentconfiguration")));
			}
			set
			{
				this.SetAttributeValue("pl_useparentconfiguration", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Status of the Autoumbering
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual pl_autonumbering_statecode? statecode
		{
			get
			{
				return ((pl_autonumbering_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Autoumbering
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual pl_autonumbering_statuscode? statuscode
		{
			get
			{
				return ((pl_autonumbering_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering> Referencedpl_AutoNumbering_AutoNumbering_ParentAutoNumberingId
		{
			get
			{
				return this.GetRelatedEntities<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering>("pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering>("pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// N:1 pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pl_parentautonumberingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering Referencingpl_AutoNumbering_AutoNumbering_ParentAutoNumberingId
		{
			get
			{
				return this.GetRelatedEntity<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering>("pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.SetRelatedEntity<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering>("pl_AutoNumbering_AutoNumbering_ParentAutoNumberingId", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
	}
}
#pragma warning restore CS1591
