#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Type of Reuse Policy associated with Copilot Studio copilot components.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum botcomponentreusepolicy
	{
		
		/// <summary>
		/// Not Reusable. By default, a copilot component is not reusable and Reuse Policy is None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		/// <summary>
		/// Is required by one or more Public copilot component, but is not directly invokable or visible
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Private = 1,
		
		/// <summary>
		/// Visible shared / reusable copilot component for use in all bots in the environment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 2,
	}
}
#pragma warning restore CS1591
