#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum botcomponentcollectionsharingroletype
	{
		
		/// <summary>
		/// Copilot user has access to the content of the component collection
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotuser = 1,
		
		/// <summary>
		/// Has access to the content of the component collection and can add component collection to the copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Componentcollectionuser = 2,
		
		/// <summary>
		/// Can author the component collection
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Componentcollectionauthor = 3,
	}
}
#pragma warning restore CS1591
