#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Options to cascade closing cases
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cascadecaseclosurepreference
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closeallchildcaseswhenparentcaseisclosed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dontallowparentcaseclosureuntilallchildcasesareclosed = 1,
	}
}
#pragma warning restore CS1591
