#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Categories for connection roles.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum connectionrole_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Business = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Family = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Social = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sales = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Stakeholder = 1000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesTeam = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 1002,
	}
}
#pragma warning restore CS1591
