#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Select the type of sales entity which the campaign response should be converted to
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_sales_entity_type
	{
		
		/// <summary>
		/// Opportunity Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 1,
		
		/// <summary>
		/// Order Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 2,
		
		/// <summary>
		/// Quote Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 3,
	}
}
#pragma warning restore CS1591
