#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Select the status for the deactivated campaign response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_deactivate_status
	{
		
		/// <summary>
		/// Closed Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 1,
		
		/// <summary>
		/// Cancelled Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 2,
	}
}
#pragma warning restore CS1591
