#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Select the option for converting the campaign response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_option
	{
		
		/// <summary>
		/// Create lead label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Createalead = 1,
		
		/// <summary>
		/// Convert to existing lead label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Converttoanexistinglead = 2,
		
		/// <summary>
		/// Create sales entity label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Createaquoteorderoropportunityforanaccountorcontact = 3,
		
		/// <summary>
		/// Close response label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closeresponse = 4,
	}
}
#pragma warning restore CS1591
