#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Select the status for the disqualified lead
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_to_lead_disqualify_status
	{
		
		/// <summary>
		/// Lost Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lost = 4,
		
		/// <summary>
		/// Cannot Contact Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CannotContact = 5,
		
		/// <summary>
		/// No Longer Interested Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoLongerInterested = 6,
		
		/// <summary>
		/// Canceled Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 7,
	}
}
#pragma warning restore CS1591
