#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// How would you like to delete this series?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum delete_recurringappointmentmaster
	{
		
		/// <summary>
		/// Delete all instances
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allinstances = 1,
		
		/// <summary>
		/// Delete all series except the past appointments
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theseriesleavepastappointments = 2,
	}
}
#pragma warning restore CS1591
