#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// The kind of dependency.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dependencytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionInternal = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 4,
	}
}
#pragma warning restore CS1591
