#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Field permission to read unmasked values.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum field_security_permission_readunmasked
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotAllowed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OneRecord = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AllRecords = 3,
	}
}
#pragma warning restore CS1591
