#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum httpmethod
	{
		
		/// <summary>
		/// GET Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GET = 0,
		
		/// <summary>
		/// POST Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		POST = 1,
		
		/// <summary>
		/// PUT Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PUT = 2,
		
		/// <summary>
		/// PATCH Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PATCH = 3,
		
		/// <summary>
		/// DELETE Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DELETE = 4,
	}
}
#pragma warning restore CS1591
