#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Information that specifies the source of the case information, such as Web, telephone, or email.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum incident_caseorigincode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Web = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 2483,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 3986,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoT = 700610000,
	}
}
#pragma warning restore CS1591
