#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Expiration State
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum knowledgearticle_expirationstate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Expired = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Archived = 5,
	}
}
#pragma warning restore CS1591
