#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum makerfewshotsqlcorrectness
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PendingValidation = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Valid = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalid = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSure = 3,
	}
}
#pragma warning restore CS1591
