#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Identifies the type of interaction
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_interactiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThumbsUp = 100230301,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThumbsDown = 100230302,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThumbsClear = 100230303,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copy = 100230304,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Generated = 100230305,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SendToCustomer = 100230306,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EditAndSend = 100230307,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManualCopy = 100230308,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Available = 100230309,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ArticleProposed = 100230310,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MarkAsReviewed = 100230311,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AcceptSuggestion = 100230312,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ViewHistory = 100230313,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExpandTile = 100230314,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RequestSolution = 100230315,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeepIt = 100230316,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Discard = 100230317,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChooseDifferentTemplate = 100230318,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TemplateSelection = 100230319,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailSent = 100230320,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailDrafted = 100230321,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecordUpdated = 100230322,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResolveCase = 100230323,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Escalate = 100230324,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TemplateRecommended = 100230325,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CheckSources = 100230326,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TemplateInstantiation = 100230327,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AboutThisSuggestion = 100230328,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Custom = 100230329,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SuggestionShown = 100230330,
	}
}
#pragma warning restore CS1591
