#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_desktopnotificationvisibility
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Never = 509180000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Whenappisinbackground = 509180001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Always = 509180002,
	}
}
#pragma warning restore CS1591
