#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_emailtemplatetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transactional = 279010000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Promotional = 279010001,
	}
}
#pragma warning restore CS1591
