#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_feature_state_option_set
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 192350010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 192350020,
	}
}
#pragma warning restore CS1591
