#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Type of attachment.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_attachmenttype
	{
		
		/// <summary>
		/// Image attachment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Image = 700610000,
		
		/// <summary>
		/// Video attachment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Video = 700610001,
	}
}
#pragma warning restore CS1591
