#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Defines type of the rule
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_unifiedroutingdiagnostic_msdyn_ruletype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DemandClassification = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RouteToQueue = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SkillIdentification = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ML = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prioritization = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Assignment = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssignmentSelectionCriteria = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Intake = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAPIClassification = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAPIRoutetoQueue = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ICDRouteToQueue = 20,
	}
}
#pragma warning restore CS1591
