#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Calculated measurements
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_iotaggregation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Avg = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Min = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Max = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sum = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Count = 192350005,
	}
}
#pragma warning restore CS1591
