#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// State of the conversation record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_conversation_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waiting = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wrapup = 4,
	}
}
#pragma warning restore CS1591
