#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_panelstateoptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Docked = 162450002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hidden = 162450001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Minimized = 162450000,
	}
}
#pragma warning restore CS1591
