#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Indicates the source of characteristic associated to the conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_conversationcharacteristicsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RuleBased = 321240000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MLBased = 321240001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 321240002,
	}
}
#pragma warning restore CS1591
