#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_actionchoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nudge = 419550000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotifySupervisor = 419550001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nudgeandthennotifysupervisor = 419550002,
	}
}
#pragma warning restore CS1591
