#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Defines type of the diagnostics record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_unifiedroutingdiagnostic_msdyn_diagnosticdatatype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DemandMLDiagnostic = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DemandClassificationDiagnostic = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DemandRTQDiagnostic = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssignmentDiagnostic = 4,
	}
}
#pragma warning restore CS1591
