#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_consentsource
	{
		
		/// <summary>
		/// Internal – Created manually or changed in the application
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = 534120000,
		
		/// <summary>
		/// Preference page - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preferencepage = 534120001,
		
		/// <summary>
		/// Text message - updated by customer via text message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Textmessage = 534120002,
		
		/// <summary>
		/// Loaded – Loaded from 'Load' button or excel upload
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Loaded = 534120003,
		
		/// <summary>
		/// Preference Center - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreferenceCenter = 534120004,
		
		/// <summary>
		/// Realtime Marketing Form - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RealtimeMarketingForm = 534120005,
		
		/// <summary>
		/// Subscription Center - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionCenter = 534120006,
		
		/// <summary>
		/// Email List unsubscribe
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Emaillistunsubscribe = 534120007,
	}
}
#pragma warning restore CS1591
