#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// This option set is used to list different Mapping Types.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_iotmappingtype
	{
		
		/// <summary>
		/// Map the device identifier.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deviceidentifier = 192350000,
		
		/// <summary>
		/// Map the rule identifier.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ruleidentifier = 192350001,
		
		/// <summary>
		/// Map a device property.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deviceproperty = 192350002,
	}
}
#pragma warning restore CS1591
