#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_queueassignmentstrategy
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OmnichannelAssignment = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoundRobin = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAssignmentConfiguration = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LongestIdle = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoAssignment = 192350005,
	}
}
#pragma warning restore CS1591
