#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// The type of an event parameter used by Cxp Events
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_eventparametertype
	{
		
		/// <summary>
		/// Event Parameter contains a Customer Identifier
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerIdentifier = 534130000,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A built-in signal property. e.g. Signal.User.Id.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CDPABuiltinSignalProperty = 534130001,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A signal property explicitly provided by the signal producer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CDPASignalProperty = 534130002,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A contactable signal property provided by the signal producer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CDPAContactableSignalProperty = 534130003,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A Event Binding signal property provided by the signal producer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CDPAEventBindingSignalProperty = 534130004,
	}
}
#pragma warning restore CS1591
