#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_source
	{
		
		/// <summary>
		/// Internal – Created manually or changed in the application
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = 534120000,
		
		/// <summary>
		/// Preference page - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preferencepage = 534120001,
		
		/// <summary>
		/// Text message - updated by customer via text message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Textmessage = 534120002,
	}
}
#pragma warning restore CS1591
