#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Status of the survey response.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_surveyresponsestatus
	{
		
		/// <summary>
		/// The survey response is partially completed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Partial = 357892000,
		
		/// <summary>
		/// The survey response is fully completed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complete = 357892001,
	}
}
#pragma warning restore CS1591
