#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// This option set is used to list different Search Types.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_iotsearchtype
	{
		
		/// <summary>
		/// The desired data is contained in a direct path.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectPath = 192350000,
		
		/// <summary>
		/// The desired data is contained in a key value path.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeyValuePath = 192350001,
	}
}
#pragma warning restore CS1591
