#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Permission level can be individual or organization
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_smstemplate_permission
	{
		
		/// <summary>
		/// Organization
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 0,
		
		/// <summary>
		/// Individual
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individual = 1,
	}
}
#pragma warning restore CS1591
