#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Stores the list of message receivers.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocmessagereceiver
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agent = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customer = 192350001,
	}
}
#pragma warning restore CS1591
