#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// category can be User/Contact/Account/Lead/Opportunity
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_smstemplate_category
	{
		
		/// <summary>
		/// Account
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		/// <summary>
		/// Contact
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		/// <summary>
		/// Opportunity
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 3,
		
		/// <summary>
		/// Lead
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		/// <summary>
		/// User
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
	}
}
#pragma warning restore CS1591
