#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyncrm_addtocalendarchoiceoptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onlytheevent = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onlysessionsregistered = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Eventandsessionsregistered = 2,
	}
}
#pragma warning restore CS1591
