#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Defines routing status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_msdyn_unifiedroutingrun_msdyn_routingstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Intakerulescompleted = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkstreamClassificationrulesprocessing = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkstreamRoutetoqueuerulescompleted = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueuePrioritizationrulescompleted = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueAssignmentselectionrulescompleted = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueAssignmentrulescompleted = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentassignmentcompleted = 100000006,
	}
}
#pragma warning restore CS1591
