#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Indicates model's recent training status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_iermlmodeltrainingstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nottrained = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Traininginprogress = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trainingcompleted = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trainingfailed = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishinprogress = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishfailed = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishcompleted = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Loadingdata = 100000007,
	}
}
#pragma warning restore CS1591
