#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// The stage of an approval and a linked approval request.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_flow_approvalstage
	{
		
		/// <summary>
		/// Not specified.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSpecified = 192350000,
		
		/// <summary>
		/// Basic stage (the single stage for Basic approvals).
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basic = 192350001,
		
		/// <summary>
		/// The approval is complete.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complete = 192351000,
	}
}
#pragma warning restore CS1591
