#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_basepresencestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Available = 192360000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Busy = 192360001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusyDND = 192360002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Away = 192360003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Offline = 192360004,
	}
}
#pragma warning restore CS1591
