#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Direct Callback Duplicate Action
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_directcallbackaction
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Playmessageanddisconnectthecall = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Playmessagebutdontendthecall = 2,
	}
}
#pragma warning restore CS1591
