#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Defines the type for ML model
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_mlmodeltype
	{
		
		/// <summary>
		/// Skill identification using ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Skillbased = 192350000,
		
		/// <summary>
		/// Routing using Sentiment ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sentimentbased = 192350001,
		
		/// <summary>
		/// Routing using Effort ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Effortbased = 192350002,
	}
}
#pragma warning restore CS1591
