#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// This option set is used to list different IoT sources.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_iotsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureIoTSuite = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureIoTCentral = 192350002,
	}
}
#pragma warning restore CS1591
