#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Define the authoring mode for the rule set
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_rulesetauthoringmode
	{
		
		/// <summary>
		/// Configure rule set with decision list control
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Decisionlist = 192350000,
	}
}
#pragma warning restore CS1591
