#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Source of the Review status of Intent or Intent Group
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_intentreviewstate_source
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIGenerated = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdminUpdated = 192350002,
	}
}
#pragma warning restore CS1591
