#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_industryoptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Automotivemobilityandtransportation = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bankingandfinancialservices = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Education = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entertainmentandmedia = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Governmentandpublicsector = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Healthcare = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Insurance = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manufacturingandindustrial = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonprofitandIGO = 192350008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Professionalandbusinessservices = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Retailandconsumergoods = 192350010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Technologyandsoftware = 192350011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Telecommunications = 192350012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 192350100,
	}
}
#pragma warning restore CS1591
