#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_externalconsentresolutionoptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Usecustomapitoresolve = 238550001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alwaysresolvetoconsentgiven = 238550002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alwaysresolvetoconsentnotgiven = 238550003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UseRealtimejourneysdefaultimplementation = 238550004,
	}
}
#pragma warning restore CS1591
