#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Type of admin role assigned to user for LOB
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_adminroletype
	{
		
		/// <summary>
		/// Discovery setup admin role for intent harvesting and curation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DiscoverySetupAdmin = 1,
		
		/// <summary>
		/// Manage intents admin role for runtime configuration and deployment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManageIntentsAdmin = 2,
	}
}
#pragma warning restore CS1591
