#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_personasecurityrolemapping_msdyn_personatype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrator = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Supervisor = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agent = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationUser = 4,
	}
}
#pragma warning restore CS1591
