#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_channelmessageparttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		plaintext = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		html = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		url = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		binary = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		image = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		record = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		number = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		boolean = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		optionlist = 192350008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		date = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		datetime = 192350010,
	}
}
#pragma warning restore CS1591
