#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Option set for selecting the type of the office document.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum officedocument_documenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftExcel = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftWord = 2,
	}
}
#pragma warning restore CS1591
