#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Plot Option referenced by configuration.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum orginsightsconfiguration_plotoption
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Line = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Column = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Area = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pie = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bar = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donut = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Infocard = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		List = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoubleDonut = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinearGauge = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bubble = 11,
	}
}
#pragma warning restore CS1591
