#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum photo_resolution
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceDefault = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_640x480 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1024x768 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1600x1200 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2048x1536 = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2592x1936 = 5,
	}
}
#pragma warning restore CS1591
