#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pl_taskstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Success = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotValid = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Error = 30,
	}
}
#pragma warning restore CS1591
