#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Power Pages Source File Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum powerpagessourcefiletype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Html = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Javascript = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CSS = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TSX = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		XML = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JSON = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yml = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebTemplate = 8,
	}
}
#pragma warning restore CS1591
