#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum powerbimashupparametervaluesource
	{
		
		/// <summary>
		/// The value for the parameter is provided as text
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Literal = 200000000,
		
		/// <summary>
		/// The value for the parameter is bound to an environment variable
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariable = 200000001,
		
		/// <summary>
		/// The value for the parameter is set to the domain of the current environment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentDomain = 200000002,
	}
}
#pragma warning restore CS1591
