#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Category of the process stage.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum processstage_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approval = 7,
	}
}
#pragma warning restore CS1591
