#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum quotecreationmethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 776160000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Revision = 776160001,
	}
}
#pragma warning restore CS1591
