#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Week of the month used under Monthly/Yearly recurrence patterns
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sameweekweek_options
	{
		
		/// <summary>
		/// First week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		First = 1,
		
		/// <summary>
		/// Second week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Second = 2,
		
		/// <summary>
		/// Third week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Third = 3,
		
		/// <summary>
		/// Fourth week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fourth = 4,
		
		/// <summary>
		/// Last week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Last = 5,
	}
}
#pragma warning restore CS1591
