#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum serviceappointment_starttime
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnyTime = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpecificTime = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RangeofTimes = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Morning = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Afternoon = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Evening = 6,
	}
}
#pragma warning restore CS1591
