#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Synapse Link external table state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkexternaltablestate
	{
		
		/// <summary>
		/// Not created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotCreated = 0,
		
		/// <summary>
		/// Created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Created = 1,
		
		/// <summary>
		/// Failed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 2,
		
		/// <summary>
		/// Deleted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 3,
		
		/// <summary>
		/// In Progress
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 4,
	}
}
#pragma warning restore CS1591
