#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Type of entity with which the activity attachment is associated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum activityfileattachment_objectcode
	{
		
		/// <summary>
		/// Post
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Post = 8000,
		
		/// <summary>
		/// Post Comment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostComment = 8005,
	}
}
#pragma warning restore CS1591
