#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum aiplugintype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataverse = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomConnector = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connector = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Flow = 3,
	}
}
#pragma warning restore CS1591
