#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum aipluginsubtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataverse = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CertifiedConnector = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QA = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Flow = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prompt = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversational = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomApi = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RestApi = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomConnector = 8,
	}
}
#pragma warning restore CS1591
