#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Cloud name for which Application Based Access List is provided. 0 is Prod, 1 is PPE , 2 is Mooncake, 3 is Arington
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum applicationbasedaccesslist_cloud
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prod = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Gallatin = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Arlington = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PPE = 3,
	}
}
#pragma warning restore CS1591
