#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum capability
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		composite = 118690000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		tabular = 118690001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		blob = 118690002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		gateway = 118690003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		cloud = 118690004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		actions = 118690005,
	}
}
#pragma warning restore CS1591
