#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum chatbotlanguage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spanish = 1034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Portuguese_Brazilian = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		French = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dutch = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Norwegian = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Danish = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Swedish = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Italian = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		German = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chinese_Simplified = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chinese_Traditional = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Arabic = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Japanese = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Korean = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hindi = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Indonesian = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Russian = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Polish = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Turkish = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thai = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Finnish = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Greek = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Czech = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English_UnitedKingdom = 2057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		French_Canada = 3084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spanish_UnitedStates = 21514,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English_Australia = 3081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hebrew = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Portuguese_Portugal = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spanish_PuertoRico = 20490,
	}
}
#pragma warning restore CS1591
