#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Select the option for converting the campaign response to a lead
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_to_lead_option
	{
		
		/// <summary>
		/// Qualify Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualifyandconvertintothefollowingrecords = 1,
		
		/// <summary>
		/// Disqualify Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disqualify = 2,
	}
}
#pragma warning restore CS1591
