#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_qualify_lead_options
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualifylead = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disqualifylead = 1,
	}
}
#pragma warning restore CS1591
