#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Option set for the different possible forms to use for incident/case resolution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum incidentresolutionformtype
	{
		
		/// <summary>
		/// MDD
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Standarddialog = 1,
		
		/// <summary>
		/// MFD
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customizabledialog = 2,
		
		/// <summary>
		/// Quick create form
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quickcreatedialog = 3,
	}
}
#pragma warning restore CS1591
