#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The sales process stage that this entity is in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum lead_salesstage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
	}
}
#pragma warning restore CS1591
