#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Dynamics 365 Languages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_languagecodes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English_enUS = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		French_frFR = 100000002,
	}
}
#pragma warning restore CS1591
