#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The set of allowed runtime types for parameter values
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_consoleapplicationparameterruntimetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@string = 110000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		number = 110000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		boolean = 110000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		json = 110000003,
	}
}
#pragma warning restore CS1591
