#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_salesagenthandovertarget
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Seller = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Supervisor = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreviousOwner = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agent = 100000003,
	}
}
#pragma warning restore CS1591
