#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_liveworkitemeventtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 192350000,
		
		/// <summary>
		/// This event is triggered when a customer initiates a conversation, that is when a live work item is created.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Created = 192350001,
		
		/// <summary>
		/// This event is triggered when the chat context is updated.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContextUpdated = 192350002,
		
		/// <summary>
		/// This event is triggered when a chat is rejoined.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerRejoin = 192350003,
		
		/// <summary>
		/// This event is triggered when a skill is updated during chat.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SkillIdentified = 192350005,
	}
}
#pragma warning restore CS1591
