#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// AI Model Task Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_aimodeltasktype
	{
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 100000000,
		
		/// <summary>
		/// QueryBoosting
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueryBoosting = 100000001,
		
		/// <summary>
		/// Classification
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Classification = 100000002,
	}
}
#pragma warning restore CS1591
