#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Denotes the level of access a participant has in a conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_conversationaccesstype
	{
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		/// <summary>
		/// Public
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 1,
		
		/// <summary>
		/// Private
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Private = 2,
	}
}
#pragma warning restore CS1591
