#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Action to be taken due to overflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_overflowactiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 192350000,
		
		/// <summary>
		/// Close the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EndConversation = 192350001,
		
		/// <summary>
		/// Transfer call to an external number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransfertoPhone = 192350002,
		
		/// <summary>
		/// Initiate callback for the customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectCallback = 192350003,
		
		/// <summary>
		/// Transfer call to voicemail
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicemail = 192350004,
		
		/// <summary>
		/// Transfer work item to another queue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueTransfer = 192350005,
		
		/// <summary>
		/// Keep work item waiting in queue for agent assignment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RemainInQueue = 192350006,
		
		/// <summary>
		/// Schedule callback for the customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScheduledCallback = 192350007,
	}
}
#pragma warning restore CS1591
