#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Available list of rich message types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocrichobjecttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebsiteRichLink = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VideoRichLink = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ListPicker = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimePicker = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomJSON = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SuggestedReply = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplePay = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Authentication = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Forms = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cards = 192350011,
	}
}
#pragma warning restore CS1591
