#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The set of allowed actions in a notification template
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_consoleapplicationnotificationaction
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allow = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deny = 100000001,
	}
}
#pragma warning restore CS1591
