#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Actions to be taken on bot failure
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_botfailureactiontype
	{
		
		/// <summary>
		/// Play a prompt and hang up the call
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PromptandHangUp = 192350000,
		
		/// <summary>
		/// Play a prompt and transfer to an external number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PromptandExternalTransfer = 192350001,
		
		/// <summary>
		/// Play a prompt and escalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PromptandEscalate = 192350002,
		
		/// <summary>
		/// Play wait music and escalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WaitMusicandEscalate = 192350003,
	}
}
#pragma warning restore CS1591
