#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Defines the step type for routing configuration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_routingconfigurationsteptype
	{
		
		/// <summary>
		/// Enriches the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enrichment = 192350000,
		
		/// <summary>
		/// Identifies the skills for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Skillidentification = 192350001,
		
		/// <summary>
		/// Identifies the queue for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queueidentification = 192350002,
		
		/// <summary>
		/// Identifies the agent group for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentGroupidentification = 192350003,
	}
}
#pragma warning restore CS1591
