#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Authentication Types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocauthenticationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OAuth20Codeflow = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OAuth20implicitflow = 192350000,
	}
}
#pragma warning restore CS1591
