#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The last session outcome options.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_lastsessionoutcome
	{
		
		/// <summary>
		/// Indicates that there was no session outcome.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 419570000,
		
		/// <summary>
		/// Indicates that the last session was abandoned.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Abandoned = 419570001,
		
		/// <summary>
		/// Indicates that the last session was escalated.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Escalated = 419570002,
		
		/// <summary>
		/// Indicates that the last session was resolved.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 419570003,
	}
}
#pragma warning restore CS1591
