#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Whether this entity is tagged for solution harvesting or not.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_harvestingtag
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotRequired = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHarvesting = 192350001,
	}
}
#pragma warning restore CS1591
