#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Defines the type of the dataverse component being used in the ruleset
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_dataversecomponenttype
	{
		
		/// <summary>
		/// Unknown
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unkown = 0,
		
		/// <summary>
		/// Routing using the custom API
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAPI = 192350000,
	}
}
#pragma warning restore CS1591
