#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_invitestatus
	{
		
		/// <summary>
		/// The customer feedback survey invite has been created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Created = 357891000,
		
		/// <summary>
		/// The customer feedback survey invite has been sent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sent = 357891001,
		
		/// <summary>
		/// The customer feedback survey invite has been responded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Responded = 357891002,
		
		/// <summary>
		/// The customer feedback survey invite is invalid
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalid = 357891003,
	}
}
#pragma warning restore CS1591
