#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The answer type expected when answering the evaluation question.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_questiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		YesNo = 700610000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Multiselectchoice = 700610001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Choosefromlist = 700610002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Text = 700610003,
	}
}
#pragma warning restore CS1591
