#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Indicates model's training status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_mltrainingstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishinprogress = 326340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishfailed = 326340002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishcompleted = 326340003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trainconfigcreated = 326340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trainingfailed = 326340004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Traininginprogress = 326340005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trainingcompleted = 326340006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishconfigcreated = 326340007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LoadingData = 326340008,
	}
}
#pragma warning restore CS1591
