#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_doijobstatus_optionset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RequestAccepted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailCreated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailPublished = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyCreated = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyPublishingStarted = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyPublished = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessingCompleted = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailCreateFailed = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailPublishFailed = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyCreateFailed = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyPublishFailed = 11,
	}
}
#pragma warning restore CS1591
