#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Denotes the mode of consultation a participant has in a conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_consultmodetype
	{
		
		/// <summary>
		/// Chat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chat = 0,
		
		/// <summary>
		/// Chat And Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChatAndVoice = 1,
		
		/// <summary>
		/// Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voice = 2,
	}
}
#pragma warning restore CS1591
