#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_assignmentconfigurationsteptype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prioritization = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssignmentRuleSelection = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Assignment = 192350002,
	}
}
#pragma warning restore CS1591
