#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_reason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noreasons = 534119999,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptinAdvertisement = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptinLandingpage = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptinEvents = 534120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutContentwasirrelevant = 534120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutReceivedtoofrequently = 534120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutDidntrecallsigningup = 534120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutPrivacyconcerns = 534120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutOneclickunsubscribe = 534120007,
	}
}
#pragma warning restore CS1591
