#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Defines type of the rule set
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_decisionrulesettype
	{
		
		/// <summary>
		/// Embellishing the work-item using conditional expressions on different entities
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Declarative = 192350000,
		
		/// <summary>
		/// Embellishing the work-item using dataverse components
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataverseComponents = 192350002,
		
		/// <summary>
		/// Embellishing the work-item using ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MLmodelbased = 192350001,
		
		/// <summary>
		/// Route conversations using an LLM model based prediction
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IntelligentConversationDistribution = 192350003,
	}
}
#pragma warning restore CS1591
