#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_evaluationcreatetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnDemand = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RealTime = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkEvaluation = 192350002,
		
		/// <summary>
		/// Option to indicate evaluation creation on trigger.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnTrigger = 192350003,
	}
}
#pragma warning restore CS1591
