#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_evaluationmethod
	{
		
		/// <summary>
		/// person reviews the AI evaluation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIassisted = 700610000,
		
		/// <summary>
		/// AI completes evaluation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIagent = 700610001,
		
		/// <summary>
		/// evaluation by a person
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 700610002,
	}
}
#pragma warning restore CS1591
