#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The status of the quality agent.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_qualityagentstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 700610000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inprogress = 700610001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 700610002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Error = 700610003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notapplicable = 700610004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Skipped = 700610005,
	}
}
#pragma warning restore CS1591
