#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Stores the list of types of system messages.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocsystemmessagetype
	{
		
		/// <summary>
		/// Automated Message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomatedMessage = 2,
		
		/// <summary>
		/// Message Template
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessageTemplate = 3,
	}
}
#pragma warning restore CS1591
