#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_statuschoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 419550000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Acknowledged = 419550001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dismissed = 419550002,
	}
}
#pragma warning restore CS1591
