#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Select whether the resource is an account, contact, user, equipment, crew, facility or a pool of resources.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_bookableresourcetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Generic = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Equipment = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Crew = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facility = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pool = 8,
	}
}
#pragma warning restore CS1591
