#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_consentlinktype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preferencepage = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Subscriptioncenter = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Externallink = 534120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preferencecenter = 534120003,
	}
}
#pragma warning restore CS1591
