#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The state of the dataflow template
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_dataflowtemplatestate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deprecated = 100000003,
	}
}
#pragma warning restore CS1591
