#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Dynamics 365 popup timeout duration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_screenpoptimeout
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_30 = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_60 = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_90 = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_120 = 120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_150 = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_180 = 180,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210 = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_240 = 240,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_270 = 270,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_300 = 300,
	}
}
#pragma warning restore CS1591
