#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Device Event
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_deviceevent
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 192350002,
	}
}
#pragma warning restore CS1591
