#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Out of the box (by default) Marketing automatically configures 3 Purpose Consents: 
	///
	///Commercial Communication 
	///Transactional Communication 
	///Tracking
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_purposetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CommercialCommunication = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransactionalCommunication = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tracking = 534120002,
	}
}
#pragma warning restore CS1591
