#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pl_logseverity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Debug = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Info = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Warning = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Error = 4,
	}
}
#pragma warning restore CS1591
