#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// The timeframe that this lead is likely to make a purchase in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum purchasetimeframe
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Immediate = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisQuarter = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NextQuarter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisYear = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 4,
	}
}
#pragma warning restore CS1591
