#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Choose when the appointment should end
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rangeends_options
	{
		
		/// <summary>
		/// The appointment series never ends
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Never = 1,
		
		/// <summary>
		/// The appointment series ends after a specified number of occurences
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bynumberofoccurrences = 2,
		
		/// <summary>
		/// The appointment series ends by a specied end date
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Byenddate = 3,
	}
}
#pragma warning restore CS1591
