#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum restapiauthtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OAuth2 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntraSSO = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		APIKey = 2,
	}
}
#pragma warning restore CS1591
