#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Day of the week used under Monthly/Yearly recurrence patterns
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sameweekday_options
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Day = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Weekday = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WeekendDay = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sunday = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monday = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tuesday = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wednesday = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thursday = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Friday = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Saturday = 9,
	}
}
#pragma warning restore CS1591
