#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum searchentity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity1 = 200004747,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity2 = 200004748,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReferencedEntity = 200004749,
	}
}
#pragma warning restore CS1591
