#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Select criteria for the selection rule
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum selection_rule_criteria
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Random_default = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeastBusy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MostBusy = 2,
	}
}
#pragma warning restore CS1591
