#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum serviceappointment_status
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoShow = 10,
	}
}
#pragma warning restore CS1591
