#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Location type of the SharePoint document location.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sharepointdocumentlocation_locationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		General = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DedicatedforOneNoteIntegration = 1,
	}
}
#pragma warning restore CS1591
