#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Validation status reason of the record URL.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sharepoint_validationstatusreason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLhasnotbeenvalidated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLisvalid = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLisnotvalid = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheURLschemesofMicrosoftDynamics365andSharePointaredifferent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheURLcouldnotbeaccessedbecauseofInternetExplorersecuritysettings = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Authenticationfailure = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalidcertificates = 7,
	}
}
#pragma warning restore CS1591
