#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Select the entity for which SLA is to be created
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sla_slaenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
	}
}
#pragma warning restore CS1591
