#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Synapse Link profile type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkprofiletype
	{
		
		/// <summary>
		/// Synapse Link profile
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SynapseLink = 0,
		
		/// <summary>
		/// Event Analytics profile
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventAnalytics = 1,
	}
}
#pragma warning restore CS1591
