#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Synapse Link table creation state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinksynapsetablecreationstate
	{
		
		/// <summary>
		/// Not started
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotStarted = 0,
		
		/// <summary>
		/// In progress
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 1,
		
		/// <summary>
		/// Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 2,
		
		/// <summary>
		/// Failed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 3,
	}
}
#pragma warning restore CS1591
