#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Type of entity with which the workflow log is associated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum workflowlog_objecttypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemJob = 4700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkflowSession = 4710,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlowSession = 4720,
	}
}
#pragma warning restore CS1591
