#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Tests
{
	
	
	/// <summary>
	/// Months in a year used under Yearly recurrence pattern
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum yearlymonth_options
	{
		
		/// <summary>
		/// January
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 1,
		
		/// <summary>
		/// February
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 2,
		
		/// <summary>
		/// March
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 3,
		
		/// <summary>
		/// April
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 4,
		
		/// <summary>
		/// May
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 5,
		
		/// <summary>
		/// June
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 6,
		
		/// <summary>
		/// July
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 7,
		
		/// <summary>
		/// August
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 8,
		
		/// <summary>
		/// September
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 9,
		
		/// <summary>
		/// October
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 10,
		
		/// <summary>
		/// November
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 11,
		
		/// <summary>
		/// December
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 12,
	}
}
#pragma warning restore CS1591
