# Auto-generated by Pillaro.Dataverse.PluginFramework NuGet package.
# Do not edit this file. It may be regenerated on build/package update.
# Configure behavior in PillaroSettings.json.
# ============================================================

param(
    [string]$Profile = 'debug'
)

Push-Location $PSScriptRoot

try {
    $settings = Join-Path $PSScriptRoot '..\..\PillaroSettings.json'
    $root = Join-Path $PSScriptRoot '..\..\..\..'

    $cliProject = Join-Path $root 'tools\Pillaro.Dataverse.PluginFramework.Cli\Pillaro.Dataverse.PluginFramework.Cli.csproj'
    $cliDll     = Join-Path $root 'tools\Pillaro.Dataverse.PluginFramework.Cli\bin\Debug\net8.0\pillaro-dv.dll'

    Write-Host "Settings:    $settings"
    Write-Host "Profile:     $Profile"
    Write-Host "Root:        $root"
    Write-Host "CLI project: $cliProject"
    Write-Host "CLI DLL:     $cliDll"

    dotnet build "$cliProject" -c Debug

    if ($LASTEXITCODE -ne 0) {
        Write-Error "CLI project build failed."
        exit $LASTEXITCODE
    }

    if (-not (Test-Path $cliDll)) {
        Write-Error "CLI DLL was not found: $cliDll"
        exit 1
    }

    if (-not (Test-Path $settings)) {
        Write-Error "Settings file was not found: $settings"
        exit 1
    }

    dotnet "$cliDll" deploy --settings "$settings" --profile "$Profile"

    exit $LASTEXITCODE
}
finally {
    Pop-Location
}
