@echo off
setlocal

REM Auto-generated by Pillaro.Dataverse.PluginFramework NuGet package.
REM Do not edit this file if it may be regenerated on build/package update.
REM Configure behavior in PillaroSettings.json.

set "SETTINGS=%~dp0..\..\PillaroSettings.json"
set "PROFILE=debug"

set "ROOT=%~dp0..\..\..\.."
set "CLI_PROJECT=%ROOT%\tools\Pillaro.Dataverse.PluginFramework.Cli\Pillaro.Dataverse.PluginFramework.Cli.csproj"
set "CLI_DLL=%ROOT%\tools\Pillaro.Dataverse.PluginFramework.Cli\bin\Debug\net8.0\pillaro-dv.dll"

echo Settings:    %SETTINGS%
echo Profile:     %PROFILE%
echo Root:        %ROOT%
echo CLI project: %CLI_PROJECT%
echo CLI DLL:     %CLI_DLL%

dotnet build "%CLI_PROJECT%" -c Debug

if errorlevel 1 (
    echo CLI project build failed.
    endlocal & exit /b 1
)

if not exist "%CLI_DLL%" (
    echo CLI DLL was not found:
    echo %CLI_DLL%
    endlocal & exit /b 1
)

dotnet "%CLI_DLL%" deploy --settings "%SETTINGS%" --profile "%PROFILE%"

set "EXIT_CODE=%ERRORLEVEL%"
endlocal & exit /b %EXIT_CODE%
