#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Select where to add the marketing list
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum addlistcampaign
	{
		
		/// <summary>
		/// To the campaign and all undistributed campaign activities.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tothecampaignandallundistributedcampaignactivities = 1,
		
		/// <summary>
		/// To the campaign only.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tothecampaignonly = 0,
	}
}
#pragma warning restore CS1591
