#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum backendtooltype
	{
		
		/// <summary>
		/// DataverseCustomAPI
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataverseCustomAPI = 0,
		
		/// <summary>
		/// ConnectorAction
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectorAction = 1,
		
		/// <summary>
		/// Graph
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Graph = 2,
		
		/// <summary>
		/// RemoteMCP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RemoteMCP = 3,
		
		/// <summary>
		/// RemoteAPI
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RemoteAPI = 4,
		
		/// <summary>
		/// SdkMessagePair
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessagePair = 5,
		
		/// <summary>
		/// BaseServerReference
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BaseServerReference = 6,
	}
}
#pragma warning restore CS1591
