#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Type of sharing roles associated with Copilot Studio agents.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum botsharingroletypes
	{
		
		/// <summary>
		/// A manager has full access to all bot content, can publish content, is accountable for bot operations, and can configure hand-off, channels and other operational information.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotmanager = 1,
		
		/// <summary>
		/// Creates, edit and maintains bot content (trigger phrases, topic content, entities and variables). USes Power Automate solutions, authentication action and other extensibility integrations (e.g. skill) provided by developers in content editing.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotauthor = 2,
		
		/// <summary>
		/// View bot performance in analytics section, monitors CSAT, provides feedback and suggestions.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotreviewer = 3,
	}
}
#pragma warning restore CS1591
