#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Do they have a budget?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum budgetstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCommittedBudget = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MayBuy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanBuy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillBuy = 3,
	}
}
#pragma warning restore CS1591
