#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Select the status for the qualified lead
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_to_lead_qualify_status
	{
		
		/// <summary>
		/// Qualified Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualified = 3,
	}
}
#pragma warning restore CS1591
