#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum convert_campaign_response_options
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Createalead = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Converttoanexistinglead = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Createaquoteorderoropportunityforanaccountorcontact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closeresponse = 3,
	}
}
#pragma warning restore CS1591
