#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Authentication protocol used when connecting to the email server.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum emailserverprofile_authenticationprotocol
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutoDetect = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Negotiate = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NTLM = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basic = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OAuth = 4,
	}
}
#pragma warning restore CS1591
