#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Full Sync Status for Data Sync Framework
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum fullsyncstate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotInitialized = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Initiating = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalid = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AcceptMerge = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 6,
	}
}
#pragma warning restore CS1591
