#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Option set for different type of update Incidents/Cases after resolution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum incidentupdateafterresolution
	{
		
		/// <summary>
		/// Don't allow updates
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dontallowupdates = 0,
		
		/// <summary>
		/// Resolved cases
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvedcases = 1,
		
		/// <summary>
		/// Canceled cases
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceledcases = 2,
		
		/// <summary>
		/// Resolved and canceled cases
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvedandcanceledcases = 3,
	}
}
#pragma warning restore CS1591
