#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum mobileofflineenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityFileAttachment = 10253,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleImage = 10262,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleAttachment = 10268,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_historicalcaseharvestbatch = 10274,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_historicalcaseharvestrun = 10275,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InterimUpdateKnowledgeArticle = 10276,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleCustomEntity = 10277,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeHarvestJobRecord = 10278,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncFnoState = 10304,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncState = 10305,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerPagesDDOSAlert = 10455,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountLeads = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContactLeads = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Property = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyAssociation = 1235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyOptionSetItem = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceListItem = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductRelationship = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unit = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitGroup = 1056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementContact = 7272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementProduct = 6363,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementTemplateProduct = 4545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentKnowledgeBaseRecord = 9931,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneToCaseProcess = 952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 10511,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDevice = 10512,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCategory = 10513,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommand = 10514,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommandDefinition = 10515,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceDataHistory = 10516,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceProperty = 10517,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceRegistrationHistory = 10518,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTPropertyDefinition = 10521,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProvider = 10522,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProviderInstance = 10523,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTSettings = 10524,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlerttoCaseProcess = 10527,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorAddress = 1004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorProduct = 1006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadCompetitors = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadProduct = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadToOpportunitySalesProcess = 954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityCompetitors = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityProduct = 1083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunitySalesProcess = 953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyInstance = 1333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvoiceProduct = 1091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteProduct = 1085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderProduct = 1089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CRMActivityMapping = 10538,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shorturl = 10737,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductMap = 10760,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAttachment = 10784,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_globalrulesetconfiguration = 10802,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_broadcastmessagebulkactionapiprivilege = 10926,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_bulkassigntoqueueapiprivilege = 10927,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_bulkforcecloseapiprivilege = 10928,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_notifyagentbulkactionapiprivilege = 10930,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelProfile = 11064,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositionCodeCategory = 11072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotknowledgeinteraction = 11124,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotVariable = 11158,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EvaluationGlobalConfig = 11176,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PAFlowRunTracker = 11184,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchAgentTrigger = 11194,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchResult = 11195,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorResearchAgentTrigger = 11196,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadAgentResult = 11199,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadDelinkResult = 11200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachAgentResult = 11202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachTriggerAgent = 11203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualificationAgentTrigger = 11204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesAgentUsage = 11206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StakeholderResearchOutput = 11207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SummarySynthesizerAgentTrigger = 11209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TargetCustomerProfilePrefillAgentResult = 11210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TargetCustomerProfilePrefillAgentTrigger = 11211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityRankerMapping = 11215,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityResearchIndicator = 11217,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityResearchUserInteractions = 11219,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RCSWatermark = 11220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity9e6e8fe9ac = 11221,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitya821cfef4d = 11241,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityf7b23384c4 = 11259,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity84abf65564 = 11277,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityf4853484c0 = 11295,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity7ea3a3f337 = 11310,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitye5704b8203 = 11316,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity44b5491e53 = 11330,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity823311c6b9 = 11344,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityd76e38c052 = 11358,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity5ccec1ec41 = 11372,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity6f82a40b76 = 11381,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity117ddc9c29 = 11383,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity40ce812592 = 11385,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity8aa30b5776 = 11387,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitydbb09dd97d = 11389,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity3b0b180d9a = 11390,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitya3e481ba14 = 11391,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityb7137badda = 11392,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityaf04824de8 = 11393,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitya989669c43 = 11394,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitybfbddc7fce = 11395,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity84c492ac28 = 11396,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity21f9ada003 = 11397,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity5cae6e9775 = 11398,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity45cf517901 = 11399,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityca24b5d258 = 11400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity8f61970890 = 11401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitydc6ba45e0c = 11402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity9b48aa6b9b = 11403,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EvaluationNotificationConfiguration = 11450,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_aiconnectormapping = 11481,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerAppsWrapBuild = 11487,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotOrganizationWorkload = 11530,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotUserWorkload = 11515,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchSummaryTrigger = 11545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AlwaysRunSQASegment = 11546,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAccountInsightsResult = 11547,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomizationAgentTrigger = 11548,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomOOBResearchResult = 11549,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultOOBAccountResearchResult = 11550,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesCompanyResolverLeadTrigger = 11551,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityAccountResearchResult = 11553,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelatedConversationTriggerTable = 11554,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataqualitylog = 11555,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataqualitysource = 11557,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataqualitysuggestion = 11558,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DQARankerTrigger = 11559,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_governanceagent_status = 11573,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_consumer_mapping = 11574,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_execution_info = 11575,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_rule = 11576,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_rule_version = 11577,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_scenariotype = 11578,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityCompetitorResearchResultCache = 11580,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrioritizedActionCatalogue = 11511,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_recommendedactionsourceagentconfig = 11582,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScreenRecordingLink = 11597,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkHarvestRunLog = 11598,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HarvestWorkItem = 11600,
	}
}
#pragma warning restore CS1591
