#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyncrm_backgroundsizetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fill_Cover = 164230000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contain = 164230001,
	}
}
#pragma warning restore CS1591
