#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Indicates the status of the individual training record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocsitrainingdatastatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 326340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 326340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Needsfurtherinvestigation = 326340002,
	}
}
#pragma warning restore CS1591
