#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_opportunityresearchtopicchoice
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealOverview = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealRisk = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealImportance = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealHealth = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NeedsandPainPoints = 100000004,
		
		/// <summary>
		/// Stakeholder Insights
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StakeholderInsights = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountInsights = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeyDealInsights = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeyUpdates = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorInsights = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelatedConversationMapping = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealSummary = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChainOfThoughts = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomResearchInsight = 100000014,
	}
}
#pragma warning restore CS1591
