#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// The mode of the OC hub being used.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocadminmode
	{
		
		/// <summary>
		/// Experience through the legacy app.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Legacy = 717210000,
		
		/// <summary>
		/// Experience through the simplified app.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Simplified = 717210001,
	}
}
#pragma warning restore CS1591
