#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Authentication setting endpoint regions
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocauthsettingendpointregions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitedStates = 192440001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canada = 192440002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitedKingdom = 192440003,
	}
}
#pragma warning restore CS1591
