#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// The panel state for a session
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_panestate
	{
		
		/// <summary>
		/// The panel will be expanded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Docked = 100000000,
		
		/// <summary>
		/// The panel will be minimized
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Minimized = 100000001,
		
		/// <summary>
		/// The panel will be hidden
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hidden = 100000002,
	}
}
#pragma warning restore CS1591
