#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_suggestiontype
	{
		
		/// <summary>
		/// Knowledge Article Suggestion
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleSuggestion = 192360000,
		
		/// <summary>
		/// Similar Case Suggestions
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SimilarCaseSuggestion = 192360001,
		
		/// <summary>
		/// Bot Suggestion
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotSuggestion = 192360002,
	}
}
#pragma warning restore CS1591
