#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Status/Outcome of an UpgradeRun, UpgradeVersion, and UpgradeStep: started/success/failure
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_upgradestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Started = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Success = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failure = 100000002,
	}
}
#pragma warning restore CS1591
