#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_mcsbotstatus
	{
		
		/// <summary>
		/// The bot is still provisioning
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 357890000,
		
		/// <summary>
		/// The bot is ready
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ready = 357890001,
		
		/// <summary>
		/// The bot is disconnected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disconnected = 357890002,
	}
}
#pragma warning restore CS1591
