#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Owner's view state: Seen, Not Seen, Hidden
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ownerviewstate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notseen = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Seen = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hidden = 2,
	}
}
#pragma warning restore CS1591
