#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Event Metadata Integration Status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_eventmetadataintegrationstatus
	{
		
		/// <summary>
		/// Unknown integration status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 534120000,
		
		/// <summary>
		/// Integrated status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Integrated = 534120001,
		
		/// <summary>
		/// Not Integrated status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotIntegrated = 534120002,
	}
}
#pragma warning restore CS1591
