#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_numberofsearchresults
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_10 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_15 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_20 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_25 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_30 = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_40 = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_50 = 6,
	}
}
#pragma warning restore CS1591
