#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Stores the list of event types for message templates.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocmessagetemplatetrigger
	{
		
		/// <summary>
		/// Outside 24-hour conversation window
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outside24hourconversationwindow = 1,
	}
}
#pragma warning restore CS1591
