#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Report Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_analyticsreporttype
	{
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 192350000,
		
		/// <summary>
		/// Published
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 192350001,
		
		/// <summary>
		/// Draft
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 192350002,
	}
}
#pragma warning restore CS1591
