#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_actiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Proposeaknowledgearticle = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvecase = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sendnextfollowup = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Replytocustomer = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Replytocustomer1 = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suggestaresolution = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Updatedcasestatus = 100000007,
	}
}
#pragma warning restore CS1591
