#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_propertytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Datetime = 192350003,
	}
}
#pragma warning restore CS1591
