#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Bot Session Outcome option
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_sessionoutcome
	{
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		none = 419550000,
		
		/// <summary>
		/// Bot Session is resolved
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		resolved = 419550001,
		
		/// <summary>
		/// Bot Session is escalated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		escalated = 419550002,
		
		/// <summary>
		/// Bot Session is abandoned
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		abandoned = 419550003,
	}
}
#pragma warning restore CS1591
