#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_applicationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityList = 509180000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRecord = 509180001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebResource = 509180002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Control = 509180003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dashboard = 509180004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Search = 509180005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThirdPartyWebsite = 509180006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Custom = 509180007,
	}
}
#pragma warning restore CS1591
