#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_consentvalue
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSet = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptedIn = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptedOut = 534120002,
	}
}
#pragma warning restore CS1591
