#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyncrm_borderstyletype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 164230000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Solid = 164230001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dotted = 164230002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dashed = 164230003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Double = 164230004,
	}
}
#pragma warning restore CS1591
