#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Show desktop notifications
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_desktopnotificationsettings
	{
		
		/// <summary>
		/// Never
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Never = 100000002,
		
		/// <summary>
		/// When app is in background
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Whenappisinbackground = 100000003,
	}
}
#pragma warning restore CS1591
