#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// This option set is used to list different Field Data Formats.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_iotfielddataformat
	{
		
		/// <summary>
		/// The field directly contains the value.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Direct = 192350000,
		
		/// <summary>
		/// The field contains a JSON containing the value desired.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JSON = 192350001,
	}
}
#pragma warning restore CS1591
