#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Event Metadata Status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_eventmetadatastatus
	{
		
		/// <summary>
		/// Draft status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 534120000,
		
		/// <summary>
		/// Published status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 534120001,
		
		/// <summary>
		/// Stopped status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Stopped = 534120002,
	}
}
#pragma warning restore CS1591
