#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Sequence Step Sub Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_sequencestep_subtype
	{
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		/// <summary>
		/// LinkedIn Action Research Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInResearch = 1,
		
		/// <summary>
		/// LinkedIn Action Get Introduced Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInGetIntroduced = 2,
		
		/// <summary>
		/// LinkedIn Action Connect Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInConnect = 3,
		
		/// <summary>
		/// LinkedIn Action InMail Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInMail = 4,
		
		/// <summary>
		/// Advance To Other Sequence
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdvanceToOtherSequence = 5,
	}
}
#pragma warning restore CS1591
