#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Whether or not an automatically-generated attribute value or attribute values has been approved by your organanization's admin.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_reviewstatus
	{
		
		/// <summary>
		/// This means that the entity has not been reviewed by user
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notapproved = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dismissed = 2,
	}
}
#pragma warning restore CS1591
