#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_agentdisplayname
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fullname = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Firstname = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lastname = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nickname = 192350003,
	}
}
#pragma warning restore CS1591
