#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_salesmicroagenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResearchAgent = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachAgent = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EngageAgent = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadReadinessAgent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DCA_ResearchAgent = 5,
		
		/// <summary>
		/// Microagent that handles the Handover process for Sales Agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HandoverMicroagent = 6,
		
		/// <summary>
		/// DCA that handles the outreach emails.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DCAOutreachagent = 7,
		
		/// <summary>
		/// DCA that handles the customer engagement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DCAEngageagent = 8,
		
		/// <summary>
		/// Email validation agent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Emailvalidationagent = 9,
		
		/// <summary>
		/// Data Enrichment - Conversation Enrichment.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesInteractionEnrichment = 10,
		
		/// <summary>
		/// Recommended actions scoring agent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recommendedactionsscoringagent = 11,
	}
}
#pragma warning restore CS1591
