#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Copilot product type picker
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_vivacopilottype
	{
		
		/// <summary>
		/// Represents records related to Sales Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		M365CopilotSales = 10000,
		
		/// <summary>
		/// Represents records related to Service Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		M365CopilotService = 10001,
		
		/// <summary>
		/// Represents records that are shared across different Copilot types
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shared = 11000,
	}
}
#pragma warning restore CS1591
