#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_salesagenthandoverintenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1Positive = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_3Negative = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2Undetected = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_4Error = 100000003,
	}
}
#pragma warning restore CS1591
