#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Option set for type of the navigation that user performed.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_visitorjourneytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PageView = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Search = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KBArticle = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAction = 192350100,
	}
}
#pragma warning restore CS1591
