#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum mspp_columnpermissionvalues
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Create = 746610000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Read = 746610001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Update = 746610002,
	}
}
#pragma warning restore CS1591
