#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Need type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum need
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Musthave = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shouldhave = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Goodtohave = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noneed = 3,
	}
}
#pragma warning restore CS1591
