#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Types of reports.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum optionset_runreport
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allapplicablerecords = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theselectedrecords = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allrecordsonallpagesincurrentview = 1,
	}
}
#pragma warning restore CS1591
