#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Product Type Code
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum qooiproduct_producttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bundle = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RequiredBundleProduct = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionalBundleProduct = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectbasedService = 5,
	}
}
#pragma warning restore CS1591
