#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Specifies whether the property is in Edit or Rectify mode.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum qooiproduct_propertiesconfigurationstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Edit = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rectify = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotConfigured = 2,
	}
}
#pragma warning restore CS1591
