#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Specifies the month of the year valid for the recurrence pattern.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum recurrencerule_monthofyear
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidMonthOfYear = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 12,
	}
}
#pragma warning restore CS1591
