#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// The resources type selector.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum resourcetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FacilityEquipment = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceGroup = 3,
	}
}
#pragma warning restore CS1591
