#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Type of connection to use with RunDesktopFlow action.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rundesktopflowconnectiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connection = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connectionreference = 2,
	}
}
#pragma warning restore CS1591
