#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Select the site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum selection_rule_sites
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thesamesite = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnySite = 1,
	}
}
#pragma warning restore CS1591
