#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Shows the service type of the SharePoint site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sharepointsite_servicetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharePoint = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OneDrive = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sharedwithme = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MSTeams = 3,
	}
}
#pragma warning restore CS1591
