#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Identifies where the social profile originated from, such as Twitter, or FaceBook.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum socialprofile_community
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cortana = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectLine = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftTeams = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectLineSpeech = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GroupMe = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Kik = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Telegram = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Skype = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Slack = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WhatsApp = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppleMessagesForBusiness = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GooglesBusinessMessages = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Line = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wechat = 4,
		
		/// <summary>
		/// Facebook item.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 1,
		
		/// <summary>
		/// Twitter.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 2,
		
		/// <summary>
		/// Other default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 0,
	}
}
#pragma warning restore CS1591
