#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link profile state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkprofilestate
	{
		
		/// <summary>
		/// Inactive
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 0,
		
		/// <summary>
		/// Active
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		/// <summary>
		/// Error
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Error = 2,
		
		/// <summary>
		/// Deleted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 3,
		
		/// <summary>
		/// Aborting
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aborting = 4,
		
		/// <summary>
		/// Aborted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aborted = 5,
		
		/// <summary>
		/// Suspended
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suspended = 6,
		
		/// <summary>
		/// Suspending
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suspending = 7,
		
		/// <summary>
		/// Deactivated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deactivated = 8,
	}
}
#pragma warning restore CS1591
