#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link entity partition strategy
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkentitypartitionstrategy
	{
		
		/// <summary>
		/// Year
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Year = 0,
		
		/// <summary>
		/// Month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Month = 1,
		
		/// <summary>
		/// HalfMonth
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HalfMonth = 2,
		
		/// <summary>
		/// FiveDay
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FiveDay = 3,
	}
}
#pragma warning restore CS1591
