#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link Entity Source
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkentitysource
	{
		
		/// <summary>
		/// Dataverse
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataverse = 0,
		
		/// <summary>
		/// FnOTables
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FnOTables = 1,
	}
}
#pragma warning restore CS1591
