#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link destination sync state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkdestinationsyncstate
	{
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		/// <summary>
		/// Not Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotCompleted = 1,
		
		/// <summary>
		/// Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 2,
	}
}
#pragma warning restore CS1591
