#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link entity metadata state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkentitymetadatastate
	{
		
		/// <summary>
		/// None state for flag enumeration. Not a valid state for usage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		/// <summary>
		/// Not created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotCreated = 1,
		
		/// <summary>
		/// Metadata creating
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MetadataCreating = 2,
		
		/// <summary>
		/// Relationship creating
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipCreating = 4,
		
		/// <summary>
		/// Created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Created = 8,
		
		/// <summary>
		/// Failure
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failure = 16,
	}
}
#pragma warning restore CS1591
