#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link entity sync state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkentitysyncstate
	{
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		/// <summary>
		/// Not started
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotStarted = 1,
		
		/// <summary>
		/// In progress
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 2,
		
		/// <summary>
		/// Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 4,
		
		/// <summary>
		/// Completed with failures
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompletedWithFailures = 8,
		
		/// <summary>
		/// Requested initial data
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RequestedInitialData = 16,
		
		/// <summary>
		/// Paused
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Paused = 32,
		
		/// <summary>
		/// Post processing
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostProcessing = 64,
	}
}
#pragma warning restore CS1591
