#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Synapse Link schedule recurrence unit
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum synapselinkschedulerecurrenceunit
	{
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		/// <summary>
		/// Minute
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Minute = 1,
		
		/// <summary>
		/// Hour
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hour = 2,
		
		/// <summary>
		/// Day
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Day = 3,
		
		/// <summary>
		/// Week
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Week = 4,
		
		/// <summary>
		/// Month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Month = 5,
		
		/// <summary>
		/// Year
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Year = 6,
	}
}
#pragma warning restore CS1591
