#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillaro.Dataverse.PluginFramework.Examples.Logic
{
	
	
	/// <summary>
	/// Options for Template Default View
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum templatedefaultview
	{
		
		/// <summary>
		/// Tiles View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TilesView = 1,
		
		/// <summary>
		/// Grid View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GridView = 2,
		
		/// <summary>
		/// List View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ListView = 3,
	}
}
#pragma warning restore CS1591
