REM Auto-generated by Pillaro.Dataverse.PluginFramework NuGet package.
REM Do not edit this file. It may be regenerated on build/package update.
REM Configure behavior in PillaroSettings.json or Tools\EarlyBound\EarlyBoundSettings.json.
@echo off
setlocal

set SETTINGS=%~dp0EarlyBoundSettings.json
set OUTPUT=%~dp0..\..\EarlyBound

pac modelbuilder build --outdirectory "%OUTPUT%" --settingsTemplateFile "%SETTINGS%"

set EXITCODE=%ERRORLEVEL%
endlocal & exit /b %EXITCODE%
