#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Pillaro.Dataverse.PluginFramework.Plugins
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class ServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public ServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering> pl_AutoNumberingSet
		{
			get
			{
				return this.CreateQuery<Pillaro.Dataverse.PluginFramework.Plugins.pl_AutoNumbering>();
			}
		}
	}
}
#pragma warning restore CS1591
